import type { Arc, CubicBezier, Line, Quad, Vec2 } from '@vitrum/geometry'

import { defaultTechnique, type TechniqueSettings } from './technique'

/**
 * The document model (F-002). This is the single source of truth for a stained glass
 * project: the lead-line network the designer draws, plus the settings and (later)
 * technique/glass/reference data derived views build on. Pieces (closed regions) are
 * NOT stored here — they are derived from the segment network by F-020, the way nets
 * are derived from a schematic in EDA. Only user intent is persisted.
 *
 * Every value in this module is plain, deeply-readonly data: no classes, no methods,
 * no hidden state. Mutation happens exclusively through commands (see `commands.ts`)
 * applied by the store (see `store.ts`), never by writing to these objects directly.
 */

/** A stable, never-reused entity id. Generated by `ids.ts` (nanoid), never index-based. */
export type SegmentId = string
export type GlassId = string
export type LayerId = string
/**
 * A detected glass piece's id (F-020). Pieces are derived, not stored; assignments key off the
 * piece's *content id* (a reproducible hash of its ring), so a saved colour resolves after reload.
 */
export type PieceId = string
/** A stable id for a network node — the shared junction two welded endpoints reference. */
export type NodeId = string

/** The geometry a segment can carry. Circular arcs only in v1 (see F-010). */
export type SegmentGeometry = Line | Arc | CubicBezier

/**
 * A network node: the authoritative position of a junction (F-013). Segment endpoints
 * reference a node by id; two endpoints are *welded* exactly when they name the same
 * node, so junction integrity (F-013 FR-1) is a structural invariant — moving the node
 * moves every incident endpoint together, and no edit can drift them apart. The node's
 * `pos` is the single source of truth; each incident segment's geometry endpoint is kept
 * bit-identical to it by the node commands.
 */
export interface Node {
  readonly pos: Vec2
}

/**
 * One edge of the lead-line network. `role` distinguishes real lead lines from
 * construction guides (which never become lead) and the panel border. `endpoints` are the
 * `[start, end]` node ids its geometry welds to: for a `Line` these are `a`/`b`, for a
 * `CubicBezier` `p0`/`p3` (handles stay free), for an `Arc` the computed start/end points.
 * The referenced nodes' positions equal those geometry endpoints exactly.
 */
export interface Segment {
  readonly id: SegmentId
  readonly geometry: SegmentGeometry
  readonly role: SegmentRole
  readonly endpoints: readonly [NodeId, NodeId]
}

export type SegmentRole = 'lead' | 'construction' | 'border'

/** Display and layout settings. Geometry is always stored in mm; units is a display concern. */
export interface ProjectSettings {
  readonly units: 'mm' | 'in'
  readonly name: string
  /** Optional panel extent in mm. */
  readonly panelSize?: { readonly width: number; readonly height: number }
}

/**
 * How light passes through a glass. Ordered roughly clear → solid; drives F-023
 * rendering and is a catalog filter facet (F-022 FR-3).
 */
export type TransparencyClass = 'transparent' | 'translucent' | 'opalescent' | 'opaque'

/** Surface texture of a glass. A catalog filter facet (F-022 FR-3). */
export type TextureTag = 'smooth' | 'hammered' | 'seedy' | 'streaky' | 'ripple' | 'granite'

/** A commercial sheet dimension a glass is sold in (mm). Dimensions only — no per-size price in v1. */
export interface SheetSize {
  readonly widthMm: number
  readonly heightMm: number
  /** Optional human label, e.g. "full sheet", "quarter". */
  readonly label?: string
}

/**
 * A glass in the catalog (F-022): the material a piece can be cut from. Instances are
 * copied by value into the project (`Project.glasses`) so a shared file is self-contained
 * and renders identically without the author's global library. User edits never mutate the
 * shipped starter catalog (copy-on-write). The optional commercial block feeds F-042/F-056
 * and keeps the shape ready for F-058 manufacturer catalogs.
 */
export interface Glass {
  readonly id: GlassId
  readonly name: string
  /** Base colour as an sRGB hex string, e.g. "#3a7bd5". The vitrail-palette swatch colour. */
  readonly color: string
  readonly transparency: TransparencyClass
  readonly texture: TextureTag
  /** Nominal thickness in mm (default 3). */
  readonly thicknessMm: number
  readonly manufacturer?: string
  readonly sku?: string
  /** Price per square metre, in the project's currency. Area-based costing only in v1. */
  readonly pricePerM2?: number
  readonly sheetSizes?: readonly SheetSize[]
  /**
   * Optional user-uploaded texture/photo swatch, embedded as a data URL. Downscaled on
   * import (cap ~512 px, F-022 FR-5) so project files stay small.
   */
  readonly swatch?: string
}

/** A content-addressed key for an embedded image blob (F-051). Stable across save/load. */
export type AssetId = string

/**
 * An embedded image blob (F-051). The *bytes* live in the `.vitrum` zip container
 * (`assets/<id>`), never in `document.json`, so the JSON stays small and text-diffable;
 * only the {@link ReferenceLayer}'s `assetId` reference is persisted in the document. This
 * type is therefore a container/runtime concern — it is not part of {@link Project}.
 */
export interface ReferenceAsset {
  readonly mime: string
  readonly bytes: Uint8Array
}

/**
 * A reference-image underlay layer (F-051): a photo or scan placed below the drawing to trace
 * over. Two quads fully describe how the image is drawn, so placement, calibration and
 * perspective correction are all just quad edits (one undo entry each):
 *
 * - `srcQuad` — four corners in **image pixel space** (TL, TR, BR, BL). Un-rectified this is the
 *   whole image `(0,0)–(w,0)–(w,h)–(0,h)`; perspective correction drags these onto the four
 *   corners of the photographed rectangle.
 * - `dstQuad` — where those corners land in **world mm space**. Move/scale/rotate/calibrate
 *   transform this quad; rectifying replaces it with the axis-aligned real rectangle.
 *
 * The renderer samples the image through the homography `dstQuad → srcQuad` (the same matrix is
 * measured against on the CPU for FR-1), so an un-rectified layer degenerates to an affine
 * placement and a rectified one warps correctly (FR-2). The image bytes are referenced by
 * `assetId` and embedded in the zip container.
 */
export interface ReferenceLayer {
  readonly id: LayerId
  readonly name: string
  readonly assetId: AssetId
  /** The imported (already downscaled) image's pixel dimensions. */
  readonly naturalWidthPx: number
  readonly naturalHeightPx: number
  readonly srcQuad: Quad
  readonly dstQuad: Quad
  /** Layer opacity, 0–1. */
  readonly opacity: number
  /** Render greyscale so it reads clearly under coloured linework. */
  readonly desaturate: boolean
  readonly visible: boolean
  /** A locked layer ignores pointer edits (no accidental drags while tracing). */
  readonly locked: boolean
  /** Whether perspective correction is active (drives which handles the UI shows). */
  readonly rectified: boolean
}

/** A stable, never-reused id for a reinforcement bar (F-032). */
export type ReinforcementId = string

/**
 * The material a reinforcement (saddle/rebar) bar is made of (F-032). A rendering/BOM concern
 * (F-042 consumes it); it does not change the structural rule, which only cares that a bar spans
 * the panel. Zinc-cored perimeter and flat steel saddle bars are the common shop choices.
 */
export type ReinforcementMaterial = 'zinc' | 'steel' | 'brass' | 'lead'

/**
 * A reinforcement bar (F-032): a straight, rigid bar laid across an assembled panel and tied to
 * the lead lines to stop it flexing, folding or bowing under its own weight. Modelled as a
 * first-class document entity (not a lead-line segment) because F-041 (print/tiling) and F-042
 * (BOM) both need it, and because the `panel-needs-reinforcement` rule consumes it. It is
 * deliberately **not** part of `segments`, so it never reaches piece detection, DRC topology or cut
 * outputs (F-020's `outputSegments` only ever sees `segments`) — a bar adds no glass piece and no
 * cut line. `a`/`b` are its endpoints in mm; `widthMm` is the bar's visual/BOM width.
 */
export interface ReinforcementBar {
  readonly id: ReinforcementId
  readonly a: Vec2
  readonly b: Vec2
  /** Bar width in mm (visual + BOM). Default 6 mm. */
  readonly widthMm: number
  readonly material: ReinforcementMaterial
}

/**
 * How serious a design-rule violation is (F-030), mirroring KiCad's ERC/DRC severities.
 * Errors block a clean panel; warnings and info are advisory. Persisted here because a
 * project may override a rule's default severity (FR-4).
 */
export type Severity = 'error' | 'warning' | 'info'

/**
 * A per-project override of a DRC rule (F-030 FR-4). Every field is optional: an entry may change
 * the severity, the enabled flag, and/or (F-031) tunable thresholds. A rule with no entry uses its
 * built-in default severity, is enabled, and takes the technique-dependent default for every
 * threshold. `thresholds` maps a rule's threshold key (e.g. `minDimensionMm`) to a pinned value
 * that overrides the shipped per-technique default; keys absent from the map keep their default.
 * The field is optional and additive, so pre-F-031 v6 files (which never carry it) load unchanged.
 */
export interface DrcRuleOverride {
  readonly severity?: Severity
  readonly enabled?: boolean
  readonly thresholds?: Readonly<Record<string, number>>
}

/**
 * A waived DRC violation (F-030 FR-3), KiCad-style. Keyed in {@link DrcState.exclusions} by the
 * violation's stable identity (rule id + involved entity ids), so it survives geometry edits as
 * long as those entities still exist. The optional `note` records *why* it was waived.
 */
export interface DrcExclusion {
  readonly note?: string
}

/**
 * The persisted design-rule state of a project (F-030). Only *intent* is stored — never the
 * derived violations themselves, which are recomputed from the network the way pieces are.
 * `exclusions` are waivers keyed by violation identity; `rules` are per-rule severity/enable
 * overrides keyed by rule id. Both default to empty (every rule at its shipped severity, nothing
 * waived).
 */
export interface DrcState {
  readonly exclusions: Readonly<Record<string, DrcExclusion>>
  readonly rules: Readonly<Record<string, DrcRuleOverride>>
}

/**
 * How pieces are numbered on the cartoon (F-040). `grouped` is the default a new project starts with
 * (Mathieu, 2026-07-20): the number encodes the glass code implicitly (`A1..An, B1..`). `sequential`
 * is a single row-major sweep (`1,2,3…`); `manual` shows only per-piece overrides.
 */
export type NumberingScheme = 'sequential' | 'grouped' | 'manual'

/**
 * Piece-numbering state (F-040). Like glass assignments, only *intent and materialised result* are
 * persisted — pieces themselves are derived. Numbers are keyed by a piece's **content id** (F-020) so
 * they survive a save/reload, and they change **only** on an explicit renumber (a workshop cartoon
 * must not shuffle mid-build): `auto` is the materialised result of the last renumber, and a piece
 * absent from both maps renders "unnumbered" until the next renumber (FR-3). `overrides` are the
 * manual per-piece labels the user typed; they win over `auto` and survive an auto-renumber (FR-1).
 * `glassCodes` maps a glass id to its short, editable code (`A, B, C…`) — the legend's key (FR-4).
 */
export interface NumberingState {
  readonly scheme: NumberingScheme
  readonly glassCodes: Readonly<Record<GlassId, string>>
  readonly auto: Readonly<Record<PieceId, string>>
  readonly overrides: Readonly<Record<PieceId, string>>
}

/**
 * Estimation factors for the cutting list and bill of materials (F-042). Only the *tunable*
 * numbers live here — everything else in the BOM is derived from geometry, glass, technique and
 * reinforcement, the way pieces and cut contours are. Every factor is user-configurable and
 * persisted (FR-5). Waste factors are fractions (`0.30` = +30%), added on top of the net quantity
 * to give the "buy this much" figure. Defaults resolved by Mathieu (2026-07-20): glass +30%,
 * came/foil +10%, solder 20 g per metre of foil seam, foil roll 33 m.
 */
export interface BomSettings {
  /** Glass area waste fraction (default 0.30 = +30%). */
  readonly glassWaste: number
  /** Came / copper-foil linear waste fraction (default 0.10 = +10%). */
  readonly leadWaste: number
  /** Solder used per metre of foil seam, in grams (default 20 g/m, beaded 60/40 both faces). */
  readonly solderGramsPerMetre: number
  /** Length of one copper-foil roll in mm, for the "number of rolls" calc (default 33 000 = 33 m). */
  readonly foilRollLengthMm: number
}

/**
 * The kind of live symmetry a project is set up with (F-052). `none` disables replication.
 * Structurally identical to `@vitrum/core`'s `SymmetryMode`; kept here so the model stays
 * core-free (the pure expansion transform lives in `@vitrum/core` and consumes this shape).
 */
export type SymmetryMode = 'none' | 'mirror' | 'double-mirror' | 'radial'

/**
 * The persisted live-symmetry setup (F-052 Decision §2) — **setup only**, never any replica
 * geometry. `center` is the mirror/rotation origin in mm; `angle` (radians) orients the primary
 * axis; `count` is the radial N-fold order (used only for `radial`, clamped ≥ 2 by the transform);
 * `mirror` adds a reflected copy per radial sector (a full dihedral group). Replicas are derived on
 * demand by `@vitrum/core`'s `expandNetwork`; only this intent is stored, so a symmetric document
 * keeps its source + this block and always has perfect symmetry until baked (FR-3).
 */
export interface SymmetrySetup {
  readonly mode: SymmetryMode
  readonly center: Vec2
  readonly angle: number
  readonly count: number
  readonly mirror: boolean
}

/** A fresh, inert symmetry setup (no replication): center at the origin, vertical primary axis. */
export function defaultSymmetry(): SymmetrySetup {
  return { mode: 'none', center: { x: 0, y: 0 }, angle: Math.PI / 2, count: 6, mirror: false }
}

/**
 * A per-piece texture placement (F-053, Glass Eye Pro Plus parity): how the glass's surface texture
 * (procedural or swatch photo) is rotated, offset and scaled within that one piece, so a streaky or
 * ripple glass can be oriented per piece the way a real cutter lays out a sheet. Stored keyed by the
 * piece's **content id** (F-020) so it survives a save/reload, exactly like glass assignments (F-023)
 * and numbering (F-040). The identity transform (0°, no offset, scale 1) is the default and is never
 * stored.
 */
export interface PieceTextureTransform {
  /** Rotation of the texture within the piece, in degrees. */
  readonly rotationDeg: number
  /** Texture offset in mm, world-axis-aligned before rotation. */
  readonly offsetXmm: number
  readonly offsetYmm: number
  /** Texture scale factor (1 = the glass's natural texture frequency). */
  readonly scale: number
}

/** The identity texture placement: unrotated, no offset, natural scale. */
export function identityTextureTransform(): PieceTextureTransform {
  return { rotationDeg: 0, offsetXmm: 0, offsetYmm: 0, scale: 1 }
}

/**
 * Realistic-render settings (F-053). Only *tunable intent* is persisted — the render itself is a
 * live derived view, never stored (the F-042 "persist intent, derive the rest" discipline).
 * `backlightIntensity`/`backlightWarmth` drive the uniform daylight backlight (F-054 later swaps in
 * the real sun); `textureTransforms` are the per-piece texture placements, keyed by piece content id
 * so they survive reload. A piece with no entry uses the identity transform.
 */
export interface RenderSettings {
  /** Uniform backlight brightness (1 = neutral daylight; 0..2 in the UI). */
  readonly backlightIntensity: number
  /** Backlight warmth, −1 (cool) … 0 (neutral) … +1 (warm). */
  readonly backlightWarmth: number
  /** Per-piece texture placement, keyed by piece content id (F-020). */
  readonly textureTransforms: Readonly<Record<PieceId, PieceTextureTransform>>
}

/** Fresh render settings: neutral full-intensity daylight, no per-piece texture placements. */
export function defaultRenderSettings(): RenderSettings {
  return { backlightIntensity: 1, backlightWarmth: 0, textureTransforms: {} }
}

/** How the sun is placed for the light simulation (F-054): by hand, or from date/time/location. */
export type LightMode = 'manual' | 'astronomical'

/**
 * Sunlight-simulation settings (F-054). Only *tunable intent* is persisted — the resolved sun and
 * the lit render are derived by `@vitrum/core`, never stored (the F-042 / F-053 discipline). One
 * block covers both modes: in `manual` mode the sun az/el, intensity and temperature are the user's
 * direct (panel-relative) values; in `astronomical` mode they are derived from location + facade
 * orientation + tilt + date/time. The halo, overcast, grain and texture toggles apply in both.
 */
export interface LightSettings {
  readonly mode: LightMode
  /** North-positive latitude, −90..90 (astronomical). */
  readonly latitudeDeg: number
  /** East-positive longitude, −180..180 (astronomical). */
  readonly longitudeDeg: number
  /** Compass direction the window front faces, 0 = N … 180 = S (astronomical). */
  readonly facadeAzimuthDeg: number
  /** Glass tilt from horizontal: 90 = vertical window, 0 = skylight (astronomical). */
  readonly tiltDeg: number
  /** Day of the year, 1..365 (astronomical). */
  readonly dayOfYear: number
  /** Local clock minutes past midnight, 0..1439 (astronomical). */
  readonly timeMinutes: number
  /** Panel-relative sun azimuth, −90 (left) … +90 (right); 0 = frontal (manual). */
  readonly manualAzimuthDeg: number
  /** Panel-relative sun elevation, 0 (horizon) … 90 (zenith) (manual). */
  readonly manualElevationDeg: number
  /** Light intensity 0..1 (manual; inert in astronomical, where the sky drives brightness). */
  readonly intensity: number
  /** Colour temperature in kelvin (manual; derived from elevation in astronomical). */
  readonly temperatureK: number
  /** Solar-halo intensity 0..1. */
  readonly haloIntensity: number
  /** Solar-halo concentration 0..1 (higher = tighter halo / rays). */
  readonly haloConcentration: number
  /** Overcast toggle: flattens and cools the light. */
  readonly overcast: boolean
  /** Photo-grain overlay on the lit stage (Diafane parity). */
  readonly photoGrain: boolean
  /** Whether glass surface textures show in the light view (Diafane parity). */
  readonly showTextures: boolean
}

/** Fresh light settings: a south-facing Amsterdam window at midsummer noon, clear sky. */
export function defaultLightSettings(): LightSettings {
  return {
    mode: 'astronomical',
    latitudeDeg: 52.37,
    longitudeDeg: 4.9,
    facadeAzimuthDeg: 180,
    tiltDeg: 90,
    dayOfYear: 172,
    timeMinutes: 12 * 60,
    manualAzimuthDeg: 0,
    manualElevationDeg: 45,
    intensity: 1,
    temperatureK: 5500,
    haloIntensity: 0.6,
    haloConcentration: 0.5,
    overcast: false,
    photoGrain: false,
    showTextures: true,
  }
}

/** The whole project. Deeply readonly; produced only by command application and load. */
export interface Project {
  readonly settings: ProjectSettings
  readonly technique: TechniqueSettings
  /**
   * The lead-line network, keyed by stable id. A record (not a `Map`) so it serializes
   * to JSON losslessly and updates via structural sharing; iteration order is insertion
   * order, which JSON round-trips preserve.
   */
  readonly segments: Readonly<Record<SegmentId, Segment>>
  /**
   * The network nodes, keyed by id (F-013). Exactly the set of node ids referenced by
   * segment endpoints — no orphans: adding/removing segments reconciles this map. A record
   * (not a `Map`) for the same lossless-JSON reasons as `segments`.
   */
  readonly nodes: Readonly<Record<NodeId, Node>>
  readonly glasses: Readonly<Record<GlassId, Glass>>
  /**
   * Glass assigned to pieces (F-023), keyed by a piece's **content id** (F-020) → a project
   * {@link GlassId}. Pieces are derived from the network, so only the assignment intent is
   * persisted; a piece with no entry renders as "unassigned". Keys are content ids (reproducible
   * from geometry) so colours survive a save/reload; assignments the save-time normaliser
   * materialises inherit across splits/merges via the detector's lineage.
   */
  readonly assignments: Readonly<Record<PieceId, GlassId>>
  readonly layers: readonly ReferenceLayer[]
  /**
   * Design-rule state (F-030): waivers and per-rule severity/enable overrides. Violations are
   * derived (never stored); only this user intent is persisted.
   */
  readonly drc: DrcState
  /**
   * Reinforcement bars laid across the panel (F-032). A separate list from `segments` precisely so
   * bars never reach piece detection or cut outputs; consumed by the `panel-needs-reinforcement`
   * rule and by F-041/F-042 exports.
   */
  readonly reinforcements: readonly ReinforcementBar[]
  /**
   * Piece-numbering state (F-040): scheme, glass codes and the materialised numbers. Derived pieces
   * are never stored; only this intent + last-renumber result is persisted.
   */
  readonly numbering: NumberingState
  /**
   * Estimation factors for the cutting list / BOM (F-042): waste factors, the solder rule of thumb
   * and the foil roll length. Only tunable intent is stored; the lists themselves are derived.
   */
  readonly bom: BomSettings
  /**
   * Live-symmetry setup (F-052): mode, center, primary-axis angle, radial count and mirror flag.
   * Setup only — replicas are derived by `@vitrum/core`, never stored. A `none` setup is the
   * inert default.
   */
  readonly symmetry: SymmetrySetup
  /**
   * Realistic-render settings (F-053): backlight intensity/warmth and per-piece texture placements.
   * Tunable intent only — the render is a derived view, never stored.
   */
  readonly render: RenderSettings
  /**
   * Sunlight-simulation settings (F-054): mode, location, facade orientation, tilt, date/time,
   * manual sun and the halo/overcast/grain/texture toggles. Tunable intent only — the resolved sun
   * and the lit stage are derived, never stored.
   */
  readonly light: LightSettings
}

const DEFAULT_SETTINGS: ProjectSettings = { units: 'mm', name: 'Untitled' }

/** A fresh numbering state: grouped-by-glass (the default), nothing numbered yet. */
export function defaultNumbering(): NumberingState {
  return { scheme: 'grouped', glassCodes: {}, auto: {}, overrides: {} }
}

/** Fresh BOM estimation factors, seeded with the resolved defaults (Mathieu, 2026-07-20). */
export function defaultBomSettings(): BomSettings {
  return { glassWaste: 0.3, leadWaste: 0.1, solderGramsPerMetre: 20, foilRollLengthMm: 33_000 }
}

/** A fresh, empty project. `settings` overrides are shallow-merged over the defaults. */
export function createEmptyProject(settings: Partial<ProjectSettings> = {}): Project {
  return {
    settings: { ...DEFAULT_SETTINGS, ...settings },
    technique: defaultTechnique(),
    segments: {},
    nodes: {},
    glasses: {},
    assignments: {},
    layers: [],
    drc: { exclusions: {}, rules: {} },
    reinforcements: [],
    numbering: defaultNumbering(),
    bom: defaultBomSettings(),
    symmetry: defaultSymmetry(),
    render: defaultRenderSettings(),
    light: defaultLightSettings(),
  }
}
