import type { Arc, CubicBezier, Line, Vec2 } from '@vitrum/geometry'

import { defaultTechnique, type TechniqueSettings } from './technique'

/**
 * The document model (F-002). This is the single source of truth for a stained glass
 * project: the lead-line network the designer draws, plus the settings and (later)
 * technique/glass/reference data derived views build on. Pieces (closed regions) are
 * NOT stored here — they are derived from the segment network by F-020, the way nets
 * are derived from a schematic in EDA. Only user intent is persisted.
 *
 * Every value in this module is plain, deeply-readonly data: no classes, no methods,
 * no hidden state. Mutation happens exclusively through commands (see `commands.ts`)
 * applied by the store (see `store.ts`), never by writing to these objects directly.
 */

/** A stable, never-reused entity id. Generated by `ids.ts` (nanoid), never index-based. */
export type SegmentId = string
export type GlassId = string
export type LayerId = string
/**
 * A detected glass piece's id (F-020). Pieces are derived, not stored; assignments key off the
 * piece's *content id* (a reproducible hash of its ring), so a saved colour resolves after reload.
 */
export type PieceId = string
/** A stable id for a network node — the shared junction two welded endpoints reference. */
export type NodeId = string

/** The geometry a segment can carry. Circular arcs only in v1 (see F-010). */
export type SegmentGeometry = Line | Arc | CubicBezier

/**
 * A network node: the authoritative position of a junction (F-013). Segment endpoints
 * reference a node by id; two endpoints are *welded* exactly when they name the same
 * node, so junction integrity (F-013 FR-1) is a structural invariant — moving the node
 * moves every incident endpoint together, and no edit can drift them apart. The node's
 * `pos` is the single source of truth; each incident segment's geometry endpoint is kept
 * bit-identical to it by the node commands.
 */
export interface Node {
  readonly pos: Vec2
}

/**
 * One edge of the lead-line network. `role` distinguishes real lead lines from
 * construction guides (which never become lead) and the panel border. `endpoints` are the
 * `[start, end]` node ids its geometry welds to: for a `Line` these are `a`/`b`, for a
 * `CubicBezier` `p0`/`p3` (handles stay free), for an `Arc` the computed start/end points.
 * The referenced nodes' positions equal those geometry endpoints exactly.
 */
export interface Segment {
  readonly id: SegmentId
  readonly geometry: SegmentGeometry
  readonly role: SegmentRole
  readonly endpoints: readonly [NodeId, NodeId]
}

export type SegmentRole = 'lead' | 'construction' | 'border'

/** Display and layout settings. Geometry is always stored in mm; units is a display concern. */
export interface ProjectSettings {
  readonly units: 'mm' | 'in'
  readonly name: string
  /** Optional panel extent in mm. */
  readonly panelSize?: { readonly width: number; readonly height: number }
}

/**
 * How light passes through a glass. Ordered roughly clear → solid; drives F-023
 * rendering and is a catalog filter facet (F-022 FR-3).
 */
export type TransparencyClass = 'transparent' | 'translucent' | 'opalescent' | 'opaque'

/** Surface texture of a glass. A catalog filter facet (F-022 FR-3). */
export type TextureTag = 'smooth' | 'hammered' | 'seedy' | 'streaky' | 'ripple' | 'granite'

/** A commercial sheet dimension a glass is sold in (mm). Dimensions only — no per-size price in v1. */
export interface SheetSize {
  readonly widthMm: number
  readonly heightMm: number
  /** Optional human label, e.g. "full sheet", "quarter". */
  readonly label?: string
}

/**
 * A glass in the catalog (F-022): the material a piece can be cut from. Instances are
 * copied by value into the project (`Project.glasses`) so a shared file is self-contained
 * and renders identically without the author's global library. User edits never mutate the
 * shipped starter catalog (copy-on-write). The optional commercial block feeds F-042/F-056
 * and keeps the shape ready for F-058 manufacturer catalogs.
 */
export interface Glass {
  readonly id: GlassId
  readonly name: string
  /** Base colour as an sRGB hex string, e.g. "#3a7bd5". The vitrail-palette swatch colour. */
  readonly color: string
  readonly transparency: TransparencyClass
  readonly texture: TextureTag
  /** Nominal thickness in mm (default 3). */
  readonly thicknessMm: number
  readonly manufacturer?: string
  readonly sku?: string
  /** Price per square metre, in the project's currency. Area-based costing only in v1. */
  readonly pricePerM2?: number
  readonly sheetSizes?: readonly SheetSize[]
  /**
   * Optional user-uploaded texture/photo swatch, embedded as a data URL. Downscaled on
   * import (cap ~512 px, F-022 FR-5) so project files stay small.
   */
  readonly swatch?: string
}

/** A reference-image underlay. Placeholder until F-051. */
export interface ReferenceLayer {
  readonly id: LayerId
  readonly name: string
  readonly visible: boolean
}

/** A stable, never-reused id for a reinforcement bar (F-032). */
export type ReinforcementId = string

/**
 * The material a reinforcement (saddle/rebar) bar is made of (F-032). A rendering/BOM concern
 * (F-042 consumes it); it does not change the structural rule, which only cares that a bar spans
 * the panel. Zinc-cored perimeter and flat steel saddle bars are the common shop choices.
 */
export type ReinforcementMaterial = 'zinc' | 'steel' | 'brass' | 'lead'

/**
 * A reinforcement bar (F-032): a straight, rigid bar laid across an assembled panel and tied to
 * the lead lines to stop it flexing, folding or bowing under its own weight. Modelled as a
 * first-class document entity (not a lead-line segment) because F-041 (print/tiling) and F-042
 * (BOM) both need it, and because the `panel-needs-reinforcement` rule consumes it. It is
 * deliberately **not** part of `segments`, so it never reaches piece detection, DRC topology or cut
 * outputs (F-020's `outputSegments` only ever sees `segments`) — a bar adds no glass piece and no
 * cut line. `a`/`b` are its endpoints in mm; `widthMm` is the bar's visual/BOM width.
 */
export interface ReinforcementBar {
  readonly id: ReinforcementId
  readonly a: Vec2
  readonly b: Vec2
  /** Bar width in mm (visual + BOM). Default 6 mm. */
  readonly widthMm: number
  readonly material: ReinforcementMaterial
}

/**
 * How serious a design-rule violation is (F-030), mirroring KiCad's ERC/DRC severities.
 * Errors block a clean panel; warnings and info are advisory. Persisted here because a
 * project may override a rule's default severity (FR-4).
 */
export type Severity = 'error' | 'warning' | 'info'

/**
 * A per-project override of a DRC rule (F-030 FR-4). Every field is optional: an entry may change
 * the severity, the enabled flag, and/or (F-031) tunable thresholds. A rule with no entry uses its
 * built-in default severity, is enabled, and takes the technique-dependent default for every
 * threshold. `thresholds` maps a rule's threshold key (e.g. `minDimensionMm`) to a pinned value
 * that overrides the shipped per-technique default; keys absent from the map keep their default.
 * The field is optional and additive, so pre-F-031 v6 files (which never carry it) load unchanged.
 */
export interface DrcRuleOverride {
  readonly severity?: Severity
  readonly enabled?: boolean
  readonly thresholds?: Readonly<Record<string, number>>
}

/**
 * A waived DRC violation (F-030 FR-3), KiCad-style. Keyed in {@link DrcState.exclusions} by the
 * violation's stable identity (rule id + involved entity ids), so it survives geometry edits as
 * long as those entities still exist. The optional `note` records *why* it was waived.
 */
export interface DrcExclusion {
  readonly note?: string
}

/**
 * The persisted design-rule state of a project (F-030). Only *intent* is stored — never the
 * derived violations themselves, which are recomputed from the network the way pieces are.
 * `exclusions` are waivers keyed by violation identity; `rules` are per-rule severity/enable
 * overrides keyed by rule id. Both default to empty (every rule at its shipped severity, nothing
 * waived).
 */
export interface DrcState {
  readonly exclusions: Readonly<Record<string, DrcExclusion>>
  readonly rules: Readonly<Record<string, DrcRuleOverride>>
}

/**
 * How pieces are numbered on the cartoon (F-040). `grouped` is the default a new project starts with
 * (Mathieu, 2026-07-20): the number encodes the glass code implicitly (`A1..An, B1..`). `sequential`
 * is a single row-major sweep (`1,2,3…`); `manual` shows only per-piece overrides.
 */
export type NumberingScheme = 'sequential' | 'grouped' | 'manual'

/**
 * Piece-numbering state (F-040). Like glass assignments, only *intent and materialised result* are
 * persisted — pieces themselves are derived. Numbers are keyed by a piece's **content id** (F-020) so
 * they survive a save/reload, and they change **only** on an explicit renumber (a workshop cartoon
 * must not shuffle mid-build): `auto` is the materialised result of the last renumber, and a piece
 * absent from both maps renders "unnumbered" until the next renumber (FR-3). `overrides` are the
 * manual per-piece labels the user typed; they win over `auto` and survive an auto-renumber (FR-1).
 * `glassCodes` maps a glass id to its short, editable code (`A, B, C…`) — the legend's key (FR-4).
 */
export interface NumberingState {
  readonly scheme: NumberingScheme
  readonly glassCodes: Readonly<Record<GlassId, string>>
  readonly auto: Readonly<Record<PieceId, string>>
  readonly overrides: Readonly<Record<PieceId, string>>
}

/** The whole project. Deeply readonly; produced only by command application and load. */
export interface Project {
  readonly settings: ProjectSettings
  readonly technique: TechniqueSettings
  /**
   * The lead-line network, keyed by stable id. A record (not a `Map`) so it serializes
   * to JSON losslessly and updates via structural sharing; iteration order is insertion
   * order, which JSON round-trips preserve.
   */
  readonly segments: Readonly<Record<SegmentId, Segment>>
  /**
   * The network nodes, keyed by id (F-013). Exactly the set of node ids referenced by
   * segment endpoints — no orphans: adding/removing segments reconciles this map. A record
   * (not a `Map`) for the same lossless-JSON reasons as `segments`.
   */
  readonly nodes: Readonly<Record<NodeId, Node>>
  readonly glasses: Readonly<Record<GlassId, Glass>>
  /**
   * Glass assigned to pieces (F-023), keyed by a piece's **content id** (F-020) → a project
   * {@link GlassId}. Pieces are derived from the network, so only the assignment intent is
   * persisted; a piece with no entry renders as "unassigned". Keys are content ids (reproducible
   * from geometry) so colours survive a save/reload; assignments the save-time normaliser
   * materialises inherit across splits/merges via the detector's lineage.
   */
  readonly assignments: Readonly<Record<PieceId, GlassId>>
  readonly layers: readonly ReferenceLayer[]
  /**
   * Design-rule state (F-030): waivers and per-rule severity/enable overrides. Violations are
   * derived (never stored); only this user intent is persisted.
   */
  readonly drc: DrcState
  /**
   * Reinforcement bars laid across the panel (F-032). A separate list from `segments` precisely so
   * bars never reach piece detection or cut outputs; consumed by the `panel-needs-reinforcement`
   * rule and by F-041/F-042 exports.
   */
  readonly reinforcements: readonly ReinforcementBar[]
  /**
   * Piece-numbering state (F-040): scheme, glass codes and the materialised numbers. Derived pieces
   * are never stored; only this intent + last-renumber result is persisted.
   */
  readonly numbering: NumberingState
}

const DEFAULT_SETTINGS: ProjectSettings = { units: 'mm', name: 'Untitled' }

/** A fresh numbering state: grouped-by-glass (the default), nothing numbered yet. */
export function defaultNumbering(): NumberingState {
  return { scheme: 'grouped', glassCodes: {}, auto: {}, overrides: {} }
}

/** A fresh, empty project. `settings` overrides are shallow-merged over the defaults. */
export function createEmptyProject(settings: Partial<ProjectSettings> = {}): Project {
  return {
    settings: { ...DEFAULT_SETTINGS, ...settings },
    technique: defaultTechnique(),
    segments: {},
    nodes: {},
    glasses: {},
    assignments: {},
    layers: [],
    drc: { exclusions: {}, rules: {} },
    reinforcements: [],
    numbering: defaultNumbering(),
  }
}
