import type { Arc, CubicBezier, Line, Vec2 } from '@vitrum/geometry'

import { defaultTechnique, type TechniqueSettings } from './technique'

/**
 * The document model (F-002). This is the single source of truth for a stained glass
 * project: the lead-line network the designer draws, plus the settings and (later)
 * technique/glass/reference data derived views build on. Pieces (closed regions) are
 * NOT stored here — they are derived from the segment network by F-020, the way nets
 * are derived from a schematic in EDA. Only user intent is persisted.
 *
 * Every value in this module is plain, deeply-readonly data: no classes, no methods,
 * no hidden state. Mutation happens exclusively through commands (see `commands.ts`)
 * applied by the store (see `store.ts`), never by writing to these objects directly.
 */

/** A stable, never-reused entity id. Generated by `ids.ts` (nanoid), never index-based. */
export type SegmentId = string
export type GlassId = string
export type LayerId = string
/** A stable id for a network node — the shared junction two welded endpoints reference. */
export type NodeId = string

/** The geometry a segment can carry. Circular arcs only in v1 (see F-010). */
export type SegmentGeometry = Line | Arc | CubicBezier

/**
 * A network node: the authoritative position of a junction (F-013). Segment endpoints
 * reference a node by id; two endpoints are *welded* exactly when they name the same
 * node, so junction integrity (F-013 FR-1) is a structural invariant — moving the node
 * moves every incident endpoint together, and no edit can drift them apart. The node's
 * `pos` is the single source of truth; each incident segment's geometry endpoint is kept
 * bit-identical to it by the node commands.
 */
export interface Node {
  readonly pos: Vec2
}

/**
 * One edge of the lead-line network. `role` distinguishes real lead lines from
 * construction guides (which never become lead) and the panel border. `endpoints` are the
 * `[start, end]` node ids its geometry welds to: for a `Line` these are `a`/`b`, for a
 * `CubicBezier` `p0`/`p3` (handles stay free), for an `Arc` the computed start/end points.
 * The referenced nodes' positions equal those geometry endpoints exactly.
 */
export interface Segment {
  readonly id: SegmentId
  readonly geometry: SegmentGeometry
  readonly role: SegmentRole
  readonly endpoints: readonly [NodeId, NodeId]
}

export type SegmentRole = 'lead' | 'construction' | 'border'

/** Display and layout settings. Geometry is always stored in mm; units is a display concern. */
export interface ProjectSettings {
  readonly units: 'mm' | 'in'
  readonly name: string
  /** Optional panel extent in mm. */
  readonly panelSize?: { readonly width: number; readonly height: number }
}

/**
 * How light passes through a glass. Ordered roughly clear → solid; drives F-023
 * rendering and is a catalog filter facet (F-022 FR-3).
 */
export type TransparencyClass = 'transparent' | 'translucent' | 'opalescent' | 'opaque'

/** Surface texture of a glass. A catalog filter facet (F-022 FR-3). */
export type TextureTag = 'smooth' | 'hammered' | 'seedy' | 'streaky' | 'ripple' | 'granite'

/** A commercial sheet dimension a glass is sold in (mm). Dimensions only — no per-size price in v1. */
export interface SheetSize {
  readonly widthMm: number
  readonly heightMm: number
  /** Optional human label, e.g. "full sheet", "quarter". */
  readonly label?: string
}

/**
 * A glass in the catalog (F-022): the material a piece can be cut from. Instances are
 * copied by value into the project (`Project.glasses`) so a shared file is self-contained
 * and renders identically without the author's global library. User edits never mutate the
 * shipped starter catalog (copy-on-write). The optional commercial block feeds F-042/F-056
 * and keeps the shape ready for F-058 manufacturer catalogs.
 */
export interface Glass {
  readonly id: GlassId
  readonly name: string
  /** Base colour as an sRGB hex string, e.g. "#3a7bd5". The vitrail-palette swatch colour. */
  readonly color: string
  readonly transparency: TransparencyClass
  readonly texture: TextureTag
  /** Nominal thickness in mm (default 3). */
  readonly thicknessMm: number
  readonly manufacturer?: string
  readonly sku?: string
  /** Price per square metre, in the project's currency. Area-based costing only in v1. */
  readonly pricePerM2?: number
  readonly sheetSizes?: readonly SheetSize[]
  /**
   * Optional user-uploaded texture/photo swatch, embedded as a data URL. Downscaled on
   * import (cap ~512 px, F-022 FR-5) so project files stay small.
   */
  readonly swatch?: string
}

/** A reference-image underlay. Placeholder until F-051. */
export interface ReferenceLayer {
  readonly id: LayerId
  readonly name: string
  readonly visible: boolean
}

/** The whole project. Deeply readonly; produced only by command application and load. */
export interface Project {
  readonly settings: ProjectSettings
  readonly technique: TechniqueSettings
  /**
   * The lead-line network, keyed by stable id. A record (not a `Map`) so it serializes
   * to JSON losslessly and updates via structural sharing; iteration order is insertion
   * order, which JSON round-trips preserve.
   */
  readonly segments: Readonly<Record<SegmentId, Segment>>
  /**
   * The network nodes, keyed by id (F-013). Exactly the set of node ids referenced by
   * segment endpoints — no orphans: adding/removing segments reconciles this map. A record
   * (not a `Map`) for the same lossless-JSON reasons as `segments`.
   */
  readonly nodes: Readonly<Record<NodeId, Node>>
  readonly glasses: Readonly<Record<GlassId, Glass>>
  readonly layers: readonly ReferenceLayer[]
}

const DEFAULT_SETTINGS: ProjectSettings = { units: 'mm', name: 'Untitled' }

/** A fresh, empty project. `settings` overrides are shallow-merged over the defaults. */
export function createEmptyProject(settings: Partial<ProjectSettings> = {}): Project {
  return {
    settings: { ...DEFAULT_SETTINGS, ...settings },
    technique: defaultTechnique(),
    segments: {},
    nodes: {},
    glasses: {},
    layers: [],
  }
}
