import type { Vec2 } from '@vitrum/geometry'

import type { DrawRole, SegmentDraft } from '../tools/types'

/**
 * Raster autotrace (F-059) — turning a scanned or photographed cartoon into editable lead lines.
 *
 * Everything in `trace/` is pure and DOM-free: pixels in, geometry out. The UI's only jobs are to
 * decode the F-051 reference layer's image bytes and hand over a flat greyscale buffer; the
 * resampling, thresholding, thinning, walking, fitting and healing all live here so they unit-test
 * in Node and could move to a worker unchanged.
 *
 * The pipeline is preprocess → binarise → despeckle → **skeletonise** → walk → simplify → fit →
 * heal (F-050's `healNetwork`, not a second implementation).
 */

/** An 8-bit greyscale raster, row-major, `data[y * width + x]` in 0–255 (0 = black). */
export interface GreyBitmap {
  readonly width: number
  readonly height: number
  readonly data: Uint8Array
}

/**
 * A 1-bit ink mask, row-major, `data[y * width + x]` ∈ {0, 1} (1 = ink). Kept separate from
 * {@link GreyBitmap} so the type says which stage a buffer belongs to.
 */
export interface InkMask {
  readonly width: number
  readonly height: number
  readonly data: Uint8Array
}

/**
 * How a pixel grid sits in the document's world millimetres. The grid is axis-aligned in world
 * space, so the mapping is a uniform scale plus a translation and traced geometry lands at true mm
 * (FR-3): pixel centre `(x + 0.5, y + 0.5)` is at `origin + (x + 0.5, y + 0.5) · mmPerPx`.
 */
export interface TraceGrid {
  readonly width: number
  readonly height: number
  /** World mm position of the grid's top-left *corner* (not the first pixel's centre). */
  readonly origin: Vec2
  readonly mmPerPx: number
}

/** Everything the trace pipeline can be tuned by — the dialog's controls, one field each. */
export interface TraceOptions {
  /**
   * Absolute luminance ceiling, 0–255: a pixel only becomes ink if it is at least this dark. This
   * is the control that does the real work on a real cartoon, because bold marker is near-black and
   * pencil annotations are mid-grey — so the threshold, not a blob-size filter, is what keeps
   * hand-written piece numbers and colour notes out of the geometry (FR-8).
   */
  readonly thresholdLuma: number
  /**
   * Radius (px) of the local-mean window for adaptive thresholding. A scan or photo of pencil on
   * paper is unevenly exposed across the sheet, so a single global cut either loses lines in the
   * shaded corner or floods the bright one; the local mean removes that gradient.
   */
  readonly adaptiveRadiusPx: number
  /** How much darker (0–255) than its local mean a pixel must be to count as ink. */
  readonly adaptiveBias: number
  /** Minimum connected ink blob area in px; smaller blobs are despeckled away. */
  readonly minBlobPx: number
  /** Douglas–Peucker tolerance in mm, applied to each skeleton run before fitting. */
  readonly simplifyMm: number
  /** Curve-fit tolerance in mm. At 0 the runs stay polylines (chains of straight segments). */
  readonly fitMm: number
  /** Healing tolerance in mm, handed to F-050's `healNetwork`. */
  readonly healMm: number
  /** The role traced strokes take in the document. */
  readonly role: DrawRole
  /**
   * Give the outermost closed contour `role: 'border'` instead of `role`. Convenient when the
   * cartoon draws its panel edge, and a guess at intent when it does not — hence off by default.
   */
  readonly outerAsBorder: boolean
}

/** A tally of what the trace did, for the dialog's read-out. */
export interface TraceSummary {
  /** Ink pixels after binarisation and despeckling. */
  readonly inkPx: number
  /** Connected ink blobs dropped by the despeckle filter. */
  readonly despeckled: number
  /** Skeleton runs found by the walk (before simplification and fitting). */
  readonly runs: number
  /** Endpoints snapped by healing. */
  readonly snapped: number
  /** Segments split at a crossing by healing. */
  readonly split: number
  /** Degenerate or duplicate segments healing dropped. */
  readonly dropped: number
}

/**
 * A previewable trace. `segments` carry **no ids** — the document mints its own on merge (the F-050
 * lesson: an id generated by an import pipeline is one more thing that can collide).
 */
export interface TraceResult {
  /** The healed traced network in world mm, ready to become drawing drafts (F-011). */
  readonly segments: readonly SegmentDraft[]
  /** The subset healing changed, for the preview's "what was healed" overlay. */
  readonly healed: readonly SegmentDraft[]
  /** The binarised mask the trace ran on — the preview the threshold control needs. */
  readonly mask: InkMask
  /** Pieces F-020 detects from the healed network: the outcome the designer tunes against. */
  readonly pieceCount: number
  readonly summary: TraceSummary
}
